# Generated by Django 4.2.7 on 2026-02-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('condition_main', models.CharField(blank=True, max_length=80)),
                ('condition_description', models.CharField(blank=True, max_length=160)),
                ('icon_code', models.CharField(blank=True, max_length=10)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted_by_user', models.BooleanField(default=False)),
                ('api_payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
