# Generated by Django 4.2.7 on 2026-02-05 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alertpreference_savedlocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedlocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedlocation',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlertPreference',
        ),
        migrations.DeleteModel(
            name='SavedLocation',
        ),
    ]
