# Generated by Django 4.2.7 on 2026-02-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_savedlocation_alertpreference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertpreference',
            unique_together=set(),
        ),
    ]
