# Generated by Django 4.2.7 on 2026-02-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_alertpreference_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpreference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_history', to='core.alertpreference')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
