# Generated by Django 4.2.7 on 2026-02-05 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alertpreference_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertpreference',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='alert_preferences',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='alertpreference',
            unique_together={('user', 'city', 'country')},
        ),
    ]
