# Generated by Django 4.2.7 on 2026-02-05 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_alertpreference_multi_alerts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathersearch',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='alertpreference',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='alerthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='core.alertpreference'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='triggered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='temperature_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='condition_description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='condition_main',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='icon_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='searched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='temperature_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='wind_speed_kph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SavedLocation',
        ),
        migrations.RemoveField(
            model_name='alertpreference',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='alertpreference',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='alertpreference',
            name='last_triggered',
        ),
        migrations.RemoveField(
            model_name='alertpreference',
            name='updated_at',
        ),
    ]
