# Generated by Django 4.2.7 on 2026-02-06 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_weathersearch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathersearch',
            options={'ordering': ['-searched_at']},
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='alerthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertpreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_history', to='core.alertpreference'),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='alerthistory',
            name='triggered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='temperature_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='city',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='condition_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='condition_main',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='humidity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='icon_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='temperature_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='wind_speed_kph',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='alertpreference',
            unique_together={('user', 'city', 'country')},
        ),
        migrations.CreateModel(
            name='SavedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'city')},
            },
        ),
    ]
