# Generated by Django 4.2.7 on 2026-02-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedlocation',
            name='favorite',
            field=models.BooleanField(default=True),
        ),
    ]
